title: Trading Brain Thesis
description: A thesis project on human-in-the-loop AI decision support for electricity trading.
exclude:
  - tests/
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
source: docs/
destination: ./_site
remote_theme: "./"
site_author: Ashley
lang: en
locale: en_US
edit_on_github: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_languages: [ruby, python, javascript, bash, yaml, markdown]
